### ISSUE TITLE
Property 'css' does not exist  error after upgrade 0.9.1 to 0.10.2 

### ISSUE THREAD

**Issue by AleksandrMalafeev** [atlassian-labs/compiled#1066]
**Describe the bug**
Upgrading @compiled/react from 0.9.1 to 0.10.2 gave me an error:

Property 'css' does not exist on type 'IntrinsicAttributes & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & StyledProps & { ...; }'.

  214 |                 <StatusInfo>
  215 |                     <StatusIcon
> 216 |                         css={{
      |                         ^
  217 |                             background: isSucceeded ? 'var(--colorSucceess)' : 'var(--colorFailure)'
  218 |                         }}
  219 |                     >

Is it a known issue?

**Comment by pancaspe87** [comment]
HI @AleksandrMalafeev,

Could you please provide more details, eg steps to replicate.
I don't think that we ever come across a similar issue.

Thanks

**Comment by mmakarin** [comment]
Same thing happening for me in 0.10.4. I'm using fork-ts-checker-webpack-plugin.

**Comment by glomotion** [comment]
@pancaspe87 Im also seeing this with `0.11.1`.

<img width="826" alt="Screen Shot 2022-10-24 at 1 50 13 pm" src="https://user-images.githubusercontent.com/1452237/197440246-04f3eb1c-d3d3-4048-b68e-0fef24e1845c.png">

repo is here: https://github.com/glomotion/compiled-issue-repro
